# Generated by Django 5.0.6 on 2024-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='type',
            field=models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient')], default='patient', max_length=7),
            preserve_default=False,
        ),
    ]
